apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - image-cache.yaml
  - vpa.yaml
  - service.yaml
  - pull-model-job.yaml
